name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [lts/*]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --immutable

      - name: Run hardhat node, deploy contracts (& generate contracts typescript output)
        run: pnpm chain & pnpm deploy

      - name: Run nextjs lint
        run: pnpm next:lint --max-warnings=0

      - name: Check typings on nextjs
        run: pnpm next:check-types

      - name: Run hardhat lint
        run: pnpm hardhat:lint --max-warnings=0
